#!/usr/bin/env bash
# oh-orchestrator — auto-creates GitHub Issues for active SDLC projects
# Runs via cron every minute on server 95.217.84.161
# Reads stages/cycles from Hub API, creates Issues with oh:ready label

set -euo pipefail

HUB="http://127.0.0.1:3901/api"
LOG="/var/log/oh-orchestrator.log"
MAX_OPEN_ISSUES=2  # max open oh:ready issues per project

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG"; }

log "oh-orchestrator starting"

# Get all active projects
PROJECTS=$(curl -sf "$HUB/projects" | jq -r '.[] | select(.active == true) | .id')

for PROJECT in $PROJECTS; do
  # Get stage info
  STAGE_DATA=$(curl -sf "$HUB/projects/$PROJECT/stages" 2>/dev/null || echo '{}')
  STAGE=$(echo "$STAGE_DATA" | jq -r '.current_stage // "sa"')
  PAUSED=$(echo "$STAGE_DATA" | jq -r '.paused // false')

  # Skip paused projects
  if [[ "$PAUSED" == "true" ]]; then
    log "SKIP $PROJECT — paused"
    continue
  fi

  # Skip manual stages (brand, fix, done)
  case "$STAGE" in
    brand|fix|done)
      log "SKIP $PROJECT — manual stage: $STAGE"
      continue
      ;;
  esac

  # Get commands for this stage from stages data
  COMMANDS=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands | keys[]" 2>/dev/null)

  for CMD in $COMMANDS; do
    CURRENT=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".current // 0")
    TARGET=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".target // 10")
    DONE=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".done // false")

    if [[ "$DONE" == "true" ]]; then
      log "DONE $PROJECT/$CMD — $CURRENT/$TARGET, trying advance"
      curl -sf -X POST "$HUB/projects/$PROJECT/stages/advance" > /dev/null 2>&1 || true
      continue
    fi

    # Check how many open oh:ready issues exist for this repo
    OPEN_COUNT=$(gh issue list -R "serter2069/$PROJECT" --label "oh:ready" --state open --json number 2>/dev/null | jq 'length' 2>/dev/null || echo "0")

    if [[ "$OPEN_COUNT" -ge "$MAX_OPEN_ISSUES" ]]; then
      log "WAIT $PROJECT/$CMD — $OPEN_COUNT open issues (max $MAX_OPEN_ISSUES)"
      continue
    fi

    # Create issue
    TITLE="run /$CMD $PROJECT (auto $((CURRENT+1))/$TARGET)"
    BODY="Auto-generated by oh-orchestrator.\n\nStage: $STAGE\nCommand: /$CMD $PROJECT\nCycle: $((CURRENT+1))/$TARGET"

    RESULT=$(gh issue create -R "serter2069/$PROJECT" \
      --title "$TITLE" \
      --body "$BODY" \
      --label "oh:ready" 2>&1 || echo "FAILED")

    if echo "$RESULT" | grep -q "FAILED"; then
      log "ERROR $PROJECT/$CMD — failed to create issue: $RESULT"
    else
      ISSUE_URL=$(echo "$RESULT" | grep -o 'https://.*')
      log "CREATED $PROJECT/$CMD — $ISSUE_URL ($((CURRENT+1))/$TARGET)"
    fi
  done
done

log "oh-orchestrator done"
