#!/usr/bin/env bash
# oh-orchestrator — auto-creates GitHub Issues for active SDLC projects
# Runs via cron every minute on server 95.217.84.161
#
# Two modes:
#   LINEAR (proto, cicd): create N "run /command" issues sequentially
#   CYCLIC (development, testing): audit→tasks→audit loop until no gaps found

set -euo pipefail

HUB="http://127.0.0.1:3901/api"
LOG="/var/log/oh-orchestrator.log"
MAX_OPEN_ISSUES=2  # max open oh:ready issues per project (for LINEAR)

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG"; }

log "oh-orchestrator starting"

# Get all active projects
PROJECTS=$(curl -sf "$HUB/projects" | jq -r '.[] | select(.active == true) | .id')

for PROJECT in $PROJECTS; do
  # Get stage info
  STAGE_DATA=$(curl -sf "$HUB/projects/$PROJECT/stages" 2>/dev/null || echo '{}')
  STAGE=$(echo "$STAGE_DATA" | jq -r '.current_stage // "sa"')
  PAUSED=$(echo "$STAGE_DATA" | jq -r '.paused // false')

  # Skip paused projects
  if [[ "$PAUSED" == "true" ]]; then
    log "SKIP $PROJECT — paused"
    continue
  fi

  # Skip local/manual stages
  case "$STAGE" in
    sa|brand|fix|testing|done)
      log "SKIP $PROJECT — local/manual stage: $STAGE"
      continue
      ;;
  esac

  # Determine mode
  case "$STAGE" in
    development) MODE="cyclic" ;;
    *)                   MODE="linear" ;;
  esac

  if [[ "$MODE" == "linear" ]]; then
    # ── LINEAR MODE (proto, cicd) ──────────────────────────────────────
    COMMANDS=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands | keys[]" 2>/dev/null)

    for CMD in $COMMANDS; do
      CURRENT=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".current // 0")
      TARGET=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".target // 10")
      DONE=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".done // false")

      if [[ "$DONE" == "true" ]]; then
        log "DONE $PROJECT/$CMD — $CURRENT/$TARGET, trying advance"
        curl -sf -X POST "$HUB/projects/$PROJECT/stages/advance" > /dev/null 2>&1 || true
        continue
      fi

      # Check open issues
      OPEN_COUNT=$(gh issue list -R "serter2069/$PROJECT" --label "oh:ready" --state open --json number 2>/dev/null | jq 'length' 2>/dev/null || echo "0")

      if [[ "$OPEN_COUNT" -ge "$MAX_OPEN_ISSUES" ]]; then
        log "WAIT $PROJECT/$CMD — $OPEN_COUNT open issues (max $MAX_OPEN_ISSUES)"
        continue
      fi

      # Create issue
      TITLE="run /$CMD $PROJECT (auto $((CURRENT+1))/$TARGET)"
      BODY="Auto-generated by oh-orchestrator.\n\nStage: $STAGE\nCommand: /$CMD $PROJECT\nCycle: $((CURRENT+1))/$TARGET"

      RESULT=$(gh issue create -R "serter2069/$PROJECT" \
        --title "$TITLE" \
        --body "$BODY" \
        --label "oh:ready" 2>&1 || echo "FAILED")

      if echo "$RESULT" | grep -q "FAILED"; then
        log "ERROR $PROJECT/$CMD — failed to create issue: $RESULT"
      else
        ISSUE_URL=$(echo "$RESULT" | grep -o 'https://.*')
        log "CREATED $PROJECT/$CMD — $ISSUE_URL ($((CURRENT+1))/$TARGET)"
      fi
    done

  else
    # ── CYCLIC MODE (development=audit, testing=dotest) ────────────────
    # Logic: audit → creates task Issues → wait for all tasks → audit again → 0 tasks = done

    CMD=""
    case "$STAGE" in
      development) CMD="audit" ;;
      testing)     CMD="dotest" ;;
    esac

    [[ -z "$CMD" ]] && continue

    # Step 1: Check if ANY open oh:ready or oh:progress issues exist (tasks still running)
    OPEN_READY=$(gh issue list -R "serter2069/$PROJECT" --label "oh:ready" --state open --json number 2>/dev/null | jq 'length' 2>/dev/null || echo "0")
    OPEN_PROGRESS=$(gh issue list -R "serter2069/$PROJECT" --label "oh:progress" --state open --json number 2>/dev/null | jq 'length' 2>/dev/null || echo "0")
    TOTAL_OPEN=$((OPEN_READY + OPEN_PROGRESS))

    if [[ "$TOTAL_OPEN" -gt 0 ]]; then
      log "CYCLIC-WAIT $PROJECT/$CMD — $TOTAL_OPEN open issues (oh:ready=$OPEN_READY, oh:progress=$OPEN_PROGRESS)"
      continue
    fi

    # Step 2: All tasks done. Check the last audit/dotest issue to see if it found gaps.
    # Look for most recent closed issue titled "run /audit" or "run /dotest"
    LAST_AUDIT=$(gh issue list -R "serter2069/$PROJECT" \
      --state closed --search "run /$CMD" --json number,title,body,labels \
      --limit 1 2>/dev/null || echo "[]")

    LAST_AUDIT_TITLE=$(echo "$LAST_AUDIT" | jq -r '.[0].title // ""')

    # Step 3: Check if the last audit reported "no gaps" / "0 issues created"
    # The audit command reports results — if it created 0 new issues, the stage is done
    LAST_AUDIT_BODY=$(echo "$LAST_AUDIT" | jq -r '.[0].body // ""')

    # Check for completion markers (audit/dotest should write this to the issue)
    if echo "$LAST_AUDIT_BODY" | grep -qi "no.* gaps\|0 issues created\|0 new issues\|all.*pass\|no.*findings\|CYCLE_COMPLETE"; then
      log "CYCLIC-DONE $PROJECT/$CMD — last audit found no gaps, advancing"
      curl -sf -X POST "$HUB/projects/$PROJECT/stages/advance" > /dev/null 2>&1 || true
      continue
    fi

    # Step 4: Need a new audit cycle. Get current cycle count.
    CURRENT=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".current // 0")
    TARGET=$(echo "$STAGE_DATA" | jq -r ".stages.\"$STAGE\".commands.\"$CMD\".target // 10")

    # Safety: don't exceed max cycles even in cyclic mode
    if [[ "$CURRENT" -ge "$TARGET" ]]; then
      log "CYCLIC-MAX $PROJECT/$CMD — reached max cycles $CURRENT/$TARGET, advancing"
      curl -sf -X POST "$HUB/projects/$PROJECT/stages/advance" > /dev/null 2>&1 || true
      continue
    fi

    # Create audit/dotest issue
    TITLE="run /$CMD $PROJECT (cycle $((CURRENT+1)))"
    BODY="Auto-generated by oh-orchestrator (CYCLIC mode).\n\nStage: $STAGE\nCommand: /$CMD $PROJECT\nCycle: $((CURRENT+1))/$TARGET\n\nThis is a cyclic stage:\n1. /$CMD analyzes the project and creates task Issues\n2. OpenHands executes all tasks\n3. When all tasks are done, /$CMD runs again\n4. If /$CMD finds no new issues → stage complete\n\nPlease add 'CYCLE_COMPLETE' to this issue body if no gaps were found."

    RESULT=$(gh issue create -R "serter2069/$PROJECT" \
      --title "$TITLE" \
      --body "$BODY" \
      --label "oh:ready" 2>&1 || echo "FAILED")

    if echo "$RESULT" | grep -q "FAILED"; then
      log "ERROR $PROJECT/$CMD — failed to create issue: $RESULT"
    else
      ISSUE_URL=$(echo "$RESULT" | grep -o 'https://.*')
      log "CYCLIC-CREATED $PROJECT/$CMD — $ISSUE_URL (cycle $((CURRENT+1)))"
    fi
  fi
done

log "oh-orchestrator done"
